name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Build and test
      run: dotnet test ./src/Tests/NetTailor.Tests/NetTailor.Tests.csproj && dotnet build -c Release

    - name: Pack NuGet package
      run: dotnet pack .src/NetTailor/NetTailor.csproj -c Release -o --include-symbols --include-source --no-build /p:PackageVersion=$(VersionTag)
      env:
        VersionTag: ${{ github.ref }}

#    - name: Publish NuGet package
#      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json