name: Publish NuGet package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.4'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and test
      run: dotnet test Tests/NetTailor.Tests && dotnet build -c Release

    - name: Publish NuGet package
      run: dotnet pack -c Release -o ./build --include-symbols --include-source --no-build /p:PackageVersion=$(VersionTag)
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
        VersionTag: ${{ github.ref }}

    - name: Upload NuGet package
      uses: actions/upload-artifact@v2
      with:
        name: NuGet package
        path: ./build/*.nupkg