name: Test NetTailor

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: [6.0.407, 7.0.202]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore ./src/NetTailor.sln

    - name: Build and test
      run: dotnet test ./src/NetTailor.sln --no-restore